# Numpy Library
This library forms a focal point for many tools we can use in our effort to develop and evaluate models. It is specifically designed for the jupyter environment to make this application (use case) simple and, once you are used to it, intuitive.

 > Time for a special super power: all things in python are 'objects' or special structures that hold attibutes (properties) and methods (functions). To get a complete list of the properties and funtions type `dir(` *obj* `)` in a code cell where *obj* can be anything even a number.  The list will be long with a number of responses starting with underscore (`_`).  The elements that don't start this way are the useful methods and properties.
 >
 > Another way to get just the list of functions without the underscore is, in a code cell, type the obj and a period (`.`) and wait a moment. [You can also hold the ctrl key and tap the spacebar] In CoLab (or a Jupyter installation with the right add-on) you will see a popup list of methods and attributes.  Leanring how to work with the '*autocomplete*' feature will speed up much of your work



In [ ]:
# @title dir() vs AutoComplete Experiment
# type "dir(23)" and run this cell.  Scroll to the bottom and note the 
#   last several responses.

# then, come back and type "23." on the next line once the kernel is running 
#   and pause after typing the '.' and note what the popup shows.


In previous examples we have used the `math` package to bring in tools for functions like $\sin()$ and $\cos()$.  This package is installed with every python implementation.  `numpy` isn't always available by default but it is easily obtained. Fortunately if you install Jupyter on your local machine and in CoLab numpy is automatically available. If you import `numpy` package you will not need the `math` package as all the same functions are built into `numpy`.

The **num**erical **py**thon package is designed to allow working with arrays of numbers with the same ease as single values (scalars).  This capability allows us to perform operations on whole arrays of values and not just on a single value. This particular feature we have seen in previous modules but here we spend a little more time with some of the more generally useful tools.  The first thing we have to do is to import the library by placing 
``` python
import numpy as np
```
as mentioned in the module on libraries, we only have to do this once at the top of a notebook.  Strictly speaking we don't need to type ` as np` but this is a common convention and one we want to continue to keep the methods in the `numpy` library distinct from other libraries.  You may notice that as you type the above line into a code cell you may get an 'autocomplete' that will suggest the rest of the line. Typing `dir(np)` will give you ~620 entries.

In [1]:
import numpy as np
len(dir(np))

619

## numpy Summary


### Array operations
A summary of useful routines to help us build and manipulate lists of numbers.

Numpy is a python library that allows you to build arrays of values easily as you would to assign a single value to a variable.  This is not intended to be an exhaustive list but a shortened one relevant to our uses.  We assume you have imported the library and set it's alias to **np**.

 - **`np.arange`**( *start*, *stop*, *incr* ) returns an np.array of values from *start* up to *stop* in *incr* steps.
    - arange will *start* with start using *incr* as a step size until the result is ≤ *stop*
    - the resulting array's length will be dependent on the value of *incr*
 - **`np.linspace`**( *start*, *stop*, *n* ) returns an np.array of values from *start* to *stop* in *n* steps.
    - linspace differs from arange in that *start* will be the first element and *stop* will be the last and there will be exactly *n* elements
    - *n* fixes the length if the array
 - **`np.array`**( *\[ an array of values ]*) returns an np.array using the provided array of explicit values.  This can be valuable to input a list of numbers from an experiment.
 - **`np.polyfit`**( *x*, *y*, *order* ) fits two correlated data values (x and y) to a polynomial of *order* 
    - linear fit means order =1, quadratic fit order = 2
    - returns an array of values starting with the highest order coefficients.
    - linear fit (order=1) the first coefficient is the slope (m) and second is intercept (b)
    
    it is easiest to set the return to a list of coefficients like
    
    `m, b = np.polyfit(... order=1)`

    - quadratic, the first coefficient is the quadratic coefficient (A), second the linear (B), etc. 

    it is easiest to set the return to a list of coefficients like

    `A, B, C = np.polyfit(... order=2)`


You can perform mathematical operations of numpy arrays as if they were single, 'scalar', values the result of which are also np.arrays.  (**N.B.** _if you need to use functions like sin, cos and exp then use the `np.` equivalent rather than the corresponding `math.` function_) 

np.arrays have a number of built in properties and methods but a short list of useful ones are (assuming the array is stored in a variable called *xx*):
 - xx**.shape** returns the structure of the array (property so no parentheses)
 - xx**.transpose()** or simply xx**.T** flips the axes of the array (sometimes necessary to present the array for better viewing)
 - xx**.max**, xx**.min**, xx**.mean**,  xx**.var**,  xx**.sum** give pretty much what you would expect from a 1D array.
 
There are other routines which may become important as we move on (discrete differences leading to derivatives and cummulative sums which lead to integrals) but we'll leave that for another time.

In [ ]:
a = np.arange(0, 5, 1)  # create an array of 1s
b = np.linspace(2.3, 7.8, 5)   # create a 5 element array from 2.3 to 7.8 in 5 steps
combo = np.array( (a, b) )  # combine them into a 2x5 array

print(f"a's shape: {a.shape}")
print(f"b's shape: {b.shape}")
print(f"combo's shape: {combo.shape}")

a's shape: (5,)
b's shape: (5,)
combo's shape: (2, 5)


In [ ]:
print(combo)  # spacing it out the long way
print("vs")
print(combo.T)  # arranging as a list of pairs the values in combo

[[0.    1.    2.    3.    4.   ]
 [2.3   3.675 5.05  6.425 7.8  ]]
vs
[[0.    2.3  ]
 [1.    3.675]
 [2.    5.05 ]
 [3.    6.425]
 [4.    7.8  ]]


### Numerical operations
In the previous installments we instroduced the standard `math` libaray. `numpy` has all the same values (plus a few more) but can perform operations on whole lists of values not just 1 like the regular library does.  This makes modelling very easy.

Here are some of the most common operations one might need.
  - `np.pi` and `np.e` are the numerical values for $\pi$ and $e$ built-in 
  - `np.sin()`, `np.cos()`, and `np.tan()` are exactly what you expect but they take radians as their input (NOT DEGREES)
  - `np.rad2deg()` and `np.deg2rad()` are the functions that convert between these angular measures
  - `np.arcsin()`, `np.arccos()`, and `np.arctan()` are, again what you expect but remmeber they return radians.  You need to use the above functions (or your own math skills) to convert to degrees.
  - `np.log()` returns the logarithm of the input in the natural base $e$ (ln() on your calculator) if you want the logarithm in base 10 you need `np.log10()`
  - The cool part about all of these, and many more is they work on arrays of values.

Works with single values...

In [15]:
print(f"π: {np.pi:20.17f} e: {np.e:20.17f}")
print(f"sin(30°): {np.sin(np.deg2rad(30)):8.3f}   sin(30 ㎭): {np.sin(30):8.3f}")
print(f"tan(45°): {np.tan(np.deg2rad(45)):8.3f}   sin(π/4):   {np.tan(np.pi/4):8.3f}")

print(f"log(100): {np.log(100):8.3f}   log10(100): {np.log10(100):8.3f}")
print(f"log(e^2):  {np.log(np.e**2):7.3f}   log10(np.e^2): {np.log10(np.e**2):5.3f}")

π:  3.14159265358979312 e:  2.71828182845904509
sin(30°):    0.500   sin(30 ㎭):   -0.988
tan(45°):    1.000   sin(π/4):      1.000
log(100):    4.605   log10(100):    2.000
log(e^2):    2.000   log10(np.e^2): 0.869


Use an array...

In [21]:
setOfAngles = np.linspace(0, 90, 6) # degrees
sinOfAngles = np.sin(np.deg2rad(setOfAngles)) # don't forget to convert degrees to radians
cosOfAngles = np.cos(np.deg2rad(setOfAngles))

with np.printoptions(precision=3, suppress=True):
    print(setOfAngles)
    print(sinOfAngles)
    print(cosOfAngles)
    # or in a nice column
    print(np.array([setOfAngles,sinOfAngles,cosOfAngles]).T)

[ 0. 18. 36. 54. 72. 90.]
[0.    0.309 0.588 0.809 0.951 1.   ]
[1.    0.951 0.809 0.588 0.309 0.   ]
[[ 0.     0.     1.   ]
 [18.     0.309  0.951]
 [36.     0.588  0.809]
 [54.     0.809  0.588]
 [72.     0.951  0.309]
 [90.     1.     0.   ]]


## scipy
Sometimes we need a little more. Scipy is worth knowing about because it has information specifically related to physical science like common constants.

The **`scipy`** package (within the scipy framework) encapsulates a large number of specialized routines that are used in scientific computing.  A fair amount of this functionality is above our current pay grade but we do want to take advantage of a couple of very useful tools. The first is a [library of constants](https://docs.scipy.org/doc/scipy/reference/constants.html).  The constants have property values and strings that signal their dimensions.

It should be noted that **`pint`** also has a large array of predefined constants but they carry their units with them and applies them to calculations as well. One of the reasons we won't use scipy very often.

In [25]:
#@title Physical Constants
import scipy.constants as pc  # get the physical constants (UNITS ARE ALWAYS SI)

print( f"{pc.c} m/s" )  # speed of light in m/s
print( f"{pc.g} m/s**2" )  # gravitational field strength in m/s^2
print( f"{pc.h} J*s" )  # Planck's constant

# Others with units and values
def printConstant(name):
  phys_const = pc.physical_constants[name];
  print(f"{name}:  {phys_const[0]:10.6} {phys_const[1]}")
  return phys_const[0]

printConstant('Newtonian constant of gravitation') # essentially in N m^2 kg^-2
e0 = printConstant('electric constant')
print(f"ke = {1/(4*pc.pi*e0):9.5g} N m^2 C^2")



299792458.0 m/s
9.80665 m/s**2
6.62607015e-34 J*s
Newtonian constant of gravitation:  6.6743e-11 m^3 kg^-1 s^-2
electric constant:  8.85419e-12 F m^-1
ke = 8.9876e+09 N m^2 C^2


In [ ]:
#@title How many physical constants?
phyConst = list(pc.physical_constants)  # fancy way to get the name of them all
num = 10
print(f"There are {len(phyConst)} in the library and here are {num} of them chosen at random")
print("---")
rgen = np.random.default_rng()
rgen.shuffle(phyConst)

for c in phyConst[:num]:
     printConstant(c)

The only other library we are likely to need is the integration library but we'll go over that if and when we need it.